"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-05-16 06:18:35.648216

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401

import postcheck.db.models  # noqa: F401  # registers _JSONType used below


# revision identifiers, used by Alembic.
revision = '0001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_slug'), ['slug'], unique=True)

    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('local_path', sa.String(), nullable=False),
    sa.Column('default_adapter', sa.String(), nullable=True),
    sa.Column('config_overrides', postcheck.db.models._JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_local_path'), ['local_path'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_org_id'), ['org_id'], unique=False)

    op.create_table('run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('since_ref', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_bugs', sa.Integer(), nullable=False),
    sa.Column('report_json', postcheck.db.models._JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_run_project_started_desc', ['project_id', 'started_at'], unique=False)

    op.create_table('bug',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('probe', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('interaction_summary', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('suspected_file', sa.String(), nullable=True),
    sa.Column('suspected_line', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('raw_event', postcheck.db.models._JSONType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bug', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bug_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_bug_run_id', ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bug', schema=None) as batch_op:
        batch_op.drop_index('ix_bug_run_id')
        batch_op.drop_index(batch_op.f('ix_bug_org_id'))

    op.drop_table('bug')
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index('ix_run_project_started_desc')
        batch_op.drop_index(batch_op.f('ix_run_project_id'))
        batch_op.drop_index(batch_op.f('ix_run_org_id'))

    op.drop_table('run')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_org_id'))
        batch_op.drop_index(batch_op.f('ix_project_local_path'))

    op.drop_table('project')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_slug'))

    op.drop_table('organization')
    # ### end Alembic commands ###
